apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:^1.26.0
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: image.tag 
    argocd-image-updater.argoproj.io/nginx.update-strategy: semver
    argocd-image-updater.argoproj.io/nginx.force-update: "true"
spec:
  destination:
    namespace: nginx-example
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-example
    repoURL: https://github.com/caiomede-tk/helm-extra-parameter-file
    targetRevision: main
